### ISSUE TITLE
Add credit for original idea of the Love Machine to Linden Lab

### ISSUE THREAD

**Issue by callumprentice** [Yelp/love#12]
The internet is littered with thousands of references to the Linden Lab Love Machine from as early as 2004. How about a credit in the docs for the original idea?

**Comment by sjaensch** [comment]
Honestly, I don't know if that's where the original idea came from.

There are not a ton of genuinely original ideas in the software industry. I don't think MySQL calls out the original inventors of SQL, or nginx the authors of the first HTTP server. Nowhere do we claim that we had this idea first, so I'm fine with leaving things as-is for now.
