### ISSUE TITLE
Fix deployment of dispatch.yaml

### ISSUE THREAD

**Issue by rockdog** [Yelp/love#3]
The current make target `deploy_with_dispatch` executes `appcfg.py --no_cookies update app.yaml worker.yaml dispatch.yaml`. But according to the documentation at https://cloud.google.com/appengine/docs/python/how-requests-are-routed the command should be `appcfg.py -A <PROJECT_ID> update_dispatch .`.

Also the make target name is confusing because it implies it deploys the app when the documented command just updates the routing information.

**Comment by sjaensch** [comment]
`update` and `update_dispatch` don't do the same thing: https://cloud.google.com/appengine/docs/python/tools/appcfg-arguments

`update` uploads a new version to App Engine (or replaces the current version if you forgot to bump the version number). It's very much not just a routing change.
