### ISSUE TITLE
Allow sending love to yourself to silently fail if using a love link from someone else

### ISSUE THREAD

**Issue by jcsnyder** [Yelp/love#30]
Our organization tends to build love links for love-bombing, like:

`https://love.url.here/?recipient=alice,bob,cathy,don,edith,frankie,grace,harriet&message=Thanks%20for%20fixing%20all%20the%20things%21
`

However, this link can't then be used by anyone who is in the list of recipients. For example, if Edith uses the link, she gets the message:

"You can love yourself, but not on YelpLove!"

This raises the barrier to using a love link for a team or group of people. Is there any way to send the love to everyone but the sending user when there's a list of recipients?

**Comment by rockdog** [comment]
Fixed with https://github.com/Yelp/love/pull/31
